services:
    redis:
        image: redis:6.2.14-bookworm
        restart: always
        ports:
            - '6379:6379'
        user: '${USER_ID}:${GROUP_ID}'
        command:
            -   /usr/local/etc/redis/redis.conf
        volumes:
            -   ./redis-data:/data
            -   ./redis-conf:/usr/local/etc/redis
